# Generated by Django 6.0.2 on 2026-02-25 12:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('aba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='questionario.aba')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('email_contato', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('faixa_etaria', models.CharField(choices=[('A18', 'Até 18'), ('19_30', '19 a 30'), ('31_40', '31 a 40'), ('41_50', '41 a 50'), ('51_60', '51 a 60'), ('60+', '60+')], max_length=10)),
                ('genero', models.CharField(choices=[('MC', 'Mulher cisgênero'), ('HC', 'Homem cisgênero'), ('MT', 'Mulher transgênero'), ('HT', 'Homem transgênero'), ('NB', 'Pessoa não binária'), ('PNR', 'Prefiro não responder'), ('OUT', 'Outro')], max_length=3)),
                ('raca', models.CharField(choices=[('IND', 'Indígena'), ('AFR', 'Afrodescendente/Preto(a)'), ('BRA', 'Branca(o)'), ('PAR', 'Mestiça(o)/Parda(o)'), ('ASI', 'Asiática(o)/Amarela(o)'), ('PNR', 'Prefiro não responder'), ('OUT', 'Outro')], max_length=3)),
                ('nome_organizacao', models.CharField(max_length=255)),
                ('localidade_organizacao', models.CharField(max_length=255)),
                ('tipo_organizacao', models.CharField(choices=[('SOC', 'Sociedade civil organizada'), ('IND', 'Indivíduo'), ('GOV', 'Instituição governamental'), ('EDU', 'Centro educacional ou de pesquisa'), ('PRI', 'Setor produtivo ou privado'), ('OUT', 'Outros')], max_length=3)),
                ('participou_projeto', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.pergunta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pergunta')},
            },
        ),
    ]
